basePath: /
definitions:
  models.Event:
    properties:
      description:
        description: Description du cours
        type: string
      end:
        description: Date et heure de fin
        type: string
      id:
        description: ID unique de l’événement
        type: string
      lastUpdate:
        description: Dernière mise à jour
        type: string
      location:
        description: Salle
        type: string
      name:
        description: Nom du cours (affiché)
        type: string
      resourceIds:
        description: IDs des resources associées
        items:
          type: string
        type: array
      start:
        description: Date et heure de début
        type: string
      uid:
        description: Identifiant unique externe
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Microservice de gestion des événements de l'emploi du temps
  title: Timetable API
  version: "1.0"
paths:
  /events:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Event'
            type: array
        "500":
          description: Erreur serveur
          schema:
            type: string
      summary: Liste tous les événements
      tags:
      - events
swagger: "2.0"
